### PR TITLE
implement the jwt token endpoint

### PR DESCRIPTION
**Pull request by did**
By doing a POST request to `/locomotive_jwt', ShopInvader will return a JWT.
Here is the JSON response:
```json
{ "token": "<JWT token>" }
```

Once decoded, you will be able to get access to the payload which follows this structure:
```json
{
  "data": {
    "site_handle": "my-site",
    "account": {
      "_id": "42",
      "email": "john@doe.net"
    }
  }
}
```

It requires the Wagon developer to create new metafields namespace for the site: `authentication`. This namespace will have 2 attributes: jwt_secret (secret key) and jwt_validity (validity of the token in seconds).

Note:
- if there is no authenticated account, the `account` key will have nil as value.

### CODE REVIEW

**Comment by did** [comment]
@Laurent-Corron @sbidoul @sebastienbeau 
Voici un première version. A en discuter semaine prochaine ?

**Comment by lmignon** [comment]
@did Thank you! It seems very simple to configure and use. We'll be back as soon as we've tested it.

**Comment by sebastienbeau** [comment]
I have done a rebase, We will start to review and test it

**Comment by sbidoul** [comment]
@sebastienbeau can we merge this and do a release of https://github.com/shopinvader/docker-locomotive-shopinvader so we can deploy?

cc/ @thibaultrey @Cedric-Pigeon

**Comment by sebastienbeau** [comment]
@sbidoul do you still need this and I merge it or I close the PR?

**Comment by sbidoul** [comment]
@sebastienbeau let's merge it.

**Pull request merged**
