### PR TITLE
[IMP] new languages

### PR DESCRIPTION
**Pull request by sylvainc**

### CODE REVIEW

**Comment by rvalyi** [comment]
Hello @sylvainc I have a doubt with theses locales with an underscore in the value. In Rails, it seems these locals have a - separator instead of _, see here https://github.com/svenfuchs/rails-i18n#usage-on-rails-23
Are you sure, of theses codes with _? Where do they come from?

**Comment by rvalyi** [comment]
Or are these the Odoo locales may be?

**Comment by sylvainc** [comment]
Hello @rvalyi,

Yes indeed the left value with dash ("-") is the value in the LocomotiveCMS Rails application, and the right value with underscore ("_") value match the language code in the name of the Algolia index which comes from the internal Odoo languages code by Shopinvader configuration/convention, maybe that could be more documented.

Thanks for your attention.

Best regards

**Comment by rvalyi** [comment]
@sylvainc all right, that's fine then. Thanks.

**Pull request merged**
